name: kubeconfigactions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nsa-security-check:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install kubescape
        run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash

      - name: scanning config files
        run: kubescape scan framework nsa *.yaml
